FROM alpine:3.12.0

ENV WORKDIR=/data/frps

# timezone
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
        apk update && \
        apk add tzdata ca-certificates && \
        cp -r -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
        rm -rf /var/cache/apk/*
        
RUN mkdir -p $WORKDIR
ADD ./ $WORKDIR
WORKDIR $WORKDIR

CMD ["./frps", "-c", "./frps.ini"]
